import java.util.concurrent.TimeUnit;

import oracle.oats.scripting.modules.basic.api.*;
import oracle.oats.scripting.modules.browser.api.*;
import oracle.oats.scripting.modules.functionalTest.api.*;
import oracle.oats.scripting.modules.utilities.api.*;
import oracle.oats.scripting.modules.utilities.api.sql.*;
import oracle.oats.scripting.modules.utilities.api.xml.*;
import oracle.oats.scripting.modules.utilities.api.file.*;
import oracle.oats.scripting.modules.webdom.api.*;

public class script extends IteratingVUserScript {
	@ScriptService oracle.oats.scripting.modules.utilities.api.UtilitiesService utilities;
	@ScriptService oracle.oats.scripting.modules.browser.api.BrowserService browser;
	@ScriptService oracle.oats.scripting.modules.functionalTest.api.FunctionalTestService ft;
	@ScriptService oracle.oats.scripting.modules.webdom.api.WebDomService web;
	@ScriptService oracle.oats.scripting.modules.datatable.api.DataTableService datatable;
	String url,uid,pwd,country,startDate,line1,line2,pO_Box,streets,city,postalCode,comments = null;
	public void initialize() throws Exception {
		browser.launch();
	}
		
	/** 
	 
	 * Add code to be executed each iteration for this virtual user.
	 */
	public void run() throws Exception {
		datatable.importExcel("C:\\OracleATS\\OFT\\Maaden\\Test Data\\HCM Employee Self Service\\HCM_SubmitExitInterviewQuestionnaire_0128.xlsx", true);
		url=(String) datatable.getValue("DataSheet", 0, "URL");
		uid=(String) datatable.getValue("DataSheet", 0, "UID");
		pwd=(String) datatable.getValue("DataSheet", 0, "PWD");		
		
		web.window("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_window}}").maximize();
		web.window("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_window}}").navigate(url);
		web.window("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_window}}").waitForPage(50, true);
		web.textBox("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.UID}}").setText(uid);
		web.textBox("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.UID}}").pressTab();
		web.textBox("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.Password}}").setPassword(pwd);
		web.button("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.Sign_In}}").click();
		web.window("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_window}}").waitForPage(150, true);
		{
			think(2.387);
		}
		web.link("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.You have a new home page}}").click();
		web.window("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_window}}").waitForPage(null);
		{
			think(4.387);
		}
		//Click on Me Tab
		if(web.link("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.Me}}").exists(50, TimeUnit.SECONDS)){
			web.link("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.Me}}").focus();
			{
				think(0.147);
			}
		web.link("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.Me}}").click();
		{
			think(3.147);
		}
		}
		//Click on Document record
		web.link("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_a_Document_Records}}").click();
		
		web.window("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_window}}").waitForPage(90, true);
		//Clik on Add button
		web.element("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_span_Add}}").focus();
		{
			think(2.741);
		}
		web.element("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_span_Add}}").click();
		web.element("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_span_Add}}").dblClick();
		{
			think(5.741);
		}
		//Select document type
		if(web.link("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_a__FOpt1__FOr1_0__FONSr2_0__1}}").exists(50, TimeUnit.SECONDS)){
			web.link("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_a__FOpt1__FOr1_0__FONSr2_0__1}}").click();
		}
		
		{
			think(2.741);
		}
		web.element("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_div__FOpt1__FOr1_0__FONSr2_0_}}").click();
		{
			think(0.482);
		}
		
		web.element("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_div__FOpt1__FOr1_0__FONSr2_0_}}").click();
		{
			think(0.415);
		}
		web.element("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_div_Exit_Interview_Questionna}}").click();
		{
			think(3.762);
		}
		web
				.textBox(
						6,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__13}}")
				.click();
		{
			think(2.779);
		}
		web
				.element(8,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_Agree_15}}")
				.click();
		{
			think(1.534);
		}
		web
				.textBox(
						9,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__14}}")
				.click();
		{
			think(1.705);
		}
		web
				.element(10,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_Agree_16}}")
				.click();
		{
			think(1.493);
		}
		web
				.textBox(
						11,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__15}}")
				.click();
		{
			think(1.422);
		}
		web
				.element(12,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_Strongly_disagree}}")
				.click();
		{
			think(1.388);
		}
		web
				.textBox(
						13,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__16}}")
				.click();
		{
			think(3.045);
		}
		web
				.element(14,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_Agree_17}}")
				.click();
		{
			think(3.025);
		}
		web
				.textBox(
						15,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__16}}")
				.pressTab();
		{
			think(0.061);
		}
		web
				.textBox(
						16,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__17}}")
				.click();
		{
			think(0.058);
		}
		web
				.element(17,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_25__6}}")
				.click();
		{
			think(0.84);
		}
		web
				.textBox(
						18,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__18}}")
				.click();
		{
			think(1.99);
		}
		web.element(19,
				"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_50_}}")
				.click();
		{
			think(1.996);
		}
		web
				.textBox(
						20,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__19}}")
				.click();
		{
			think(6.914);
		}
		web
				.link(
						21,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_a__FOpt1__FOr1_0__FONSr2_0__30}}")
				.click();
		{
			think(2.823);
		}
		web.element(22,
				"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_td___2}}")
				.click();
		{
			think(2.334);
		}
		web
				.textBox(
						23,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__20}}")
				.click();
		{
			think(1.642);
		}
		web
				.element(24,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_50__1}}")
				.click();
		{
			think(2.619);
		}
		web
				.textBox(
						25,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__21}}")
				.click();
		{
			think(1.408);
		}
		web.element(26,
				"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_75_}}")
				.click();
		{
			think(1.704);
		}
		web
				.textBox(
						27,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__22}}")
				.click();
		{
			think(1.333);
		}
		web
				.element(28,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_25__7}}")
				.click();
		{
			think(1.823);
		}
		web
				.textBox(
						29,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__22}}")
				.pressTab();
		{
			think(0.057);
		}
		web
				.textBox(
						30,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__23}}")
				.click();
		{
			think(0.053);
		}
		web
				.element(31,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_25__8}}")
				.click();
		{
			think(0.107);
		}
		web
				.textBox(
						32,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__24}}")
				.click();
		{
			think(0.165);
		}
		web
				.element(33,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_50__2}}")
				.click();
		{
			think(1.235);
		}
		web
				.textBox(
						34,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__25}}")
				.click();
		{
			think(2.662);
		}
		web
				.link(
						35,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_a__FOpt1__FOr1_0__FONSr2_0__31}}")
				.click();
		{
			think(2.222);
		}
		web.element(36,
				"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_td_75_}}")
				.click();
		{
			think(4.347);
		}
		web
				.element(37,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_html_1_3}}")
				.click();
		{
			think(4.227);
		}
		web
				.textBox(
						38,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__26}}")
				.click();
		{
			think(8.481);
		}
		web
				.textBox(
						39,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__27}}")
				.click();
		{
			think(1.925);
		}
		web
				.element(40,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_Agree_18}}")
				.click();
		{
			think(1.512);
		}
		web
				.textBox(
						41,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__28}}")
				.click();
		{
			think(1.088);
		}
		web
				.element(42,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_Agree_19}}")
				.click();
		{
			think(1.115);
		}
		web
				.textBox(
						43,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__29}}")
				.click();
		{
			think(1.05);
		}
		web
				.element(44,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_Agree_20}}")
				.click();
		{
			think(3.006);
		}
		web
				.textBox(
						45,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__30}}")
				.click();
		{
			think(3.918);
		}
		web
				.link(
						46,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_a__FOpt1__FOr1_0__FONSr2_0__32}}")
				.click();
		{
			think(2.666);
		}
		web
				.element(47,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_td_Agree}}")
				.click();
		{
			think(3.834);
		}
		web
				.element(
						48,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_div_Document_DetailsView_Docu}}")
				.click();
		{
			think(3.486);
		}
		web
				.element(49,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_html_1_3}}")
				.click();
		{
			think(2.081);
		}
		web
				.textBox(
						50,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__31}}")
				.click();
		{
			think(1.555);
		}
		web
				.element(
						51,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_Neither_agree_nor_disagre}}")
				.click();
		{
			think(1.184);
		}
		web
				.textBox(
						52,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__32}}")
				.click();
		{
			think(1.205);
		}
		web
				.element(
						53,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_Neither_agree_nor_disagre_1}}")
				.click();
		{
			think(1.129);
		}
		web
				.textBox(
						54,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__33}}")
				.click();
		{
			think(1.075);
		}
		web
				.element(
						55,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_Neither_agree_nor_disagre_2}}")
				.click();
		{
			think(1.182);
		}
		web
				.textBox(
						56,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__34}}")
				.click();
		{
			think(0.892);
		}
		web
				.element(
						57,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_Neither_agree_nor_disagre_3}}")
				.click();
		{
			think(1.215);
		}
		web
				.textBox(
						58,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__35}}")
				.click();
		{
			think(1.18);
		}
		web
				.element(
						59,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_Neither_agree_nor_disagre_4}}")
				.click();
		{
			think(1.234);
		}
		web
				.textBox(
						60,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__36}}")
				.click();
		{
			think(1.08);
		}
		web
				.element(
						61,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_Neither_agree_nor_disagre_5}}")
				.click();
		{
			think(1.186);
		}
		web
				.textBox(
						62,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_input_text__FOpt1__FOr1_0__FONSr2_0__37}}")
				.click();
		{
			think(1.129);
		}
		web
				.element(63,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_li_Agree_21}}")
				.click();
		{
			think(4.367);
		}
		web
				.element(64,
						"{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_html_1_3}}")
				.click();
	}
	public void finish() throws Exception {
		//SignOut

//		web.element("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_svg_true_3}}").click();
//		{
//		think(5.819);
//		}
//		web.link("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_a__FOpt1__UISlg1_1}}").click();		
//		web.window("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_window}}").waitForPage(90, true);
//		{
//			think(5.819);
//		}
//
//		web.window("{{obj.HCM_SubmitExitInterviewQuestionnaire_0128.web_window}}").close();
//		

	}
}